services:
  downstream-mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - cdc_default
    restart: always
    ports:
      - "3307:3307"
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_USER=user
      - MYSQL_PASSWORD=12345678
    volumes:
      - ./mysql-data:/var/lib/mysql

networks:
  cdc_default:
    external: true
